import Navbar from "./components/Navbar";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import ReduxProvider from "@/store/Provider";
import { ToastContainer } from "react-toastify";

const lato = localFont({
  src: [
    {
      path: './fonts/Lato-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-lato',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable}>
      <body>
        <ToastContainer />
        <Navbar />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
